services:
  web:
    depends_on:
      - back
    build: ./front
    image: front
    container_name: front
    networks:
      - simple-crud-network
    restart: unless-stopped
    ports:
      - "80:3006"
    env_file:
      - ./.prod.env
    volumes:
      - ./dataAssets:/app/dist/data

  back:
    # depends_on:
    #   - pgsql
    build: ./back
    image: back
    container_name: back
    networks:
      - simple-crud-network
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=localhost
      - DATABASE_URL=postgres://pguser:pgpassword@127.0.0.1:5432/postgres
    env_file:
      - ./.prod.env
    volumes:
      - ./dataAssets:/app/data

  # pgsql:
  #   image: postgres:alpine
  #   ports:
  #     - '5432:5432'
  #   container_name: 'pgsql'
  #   networks:
  #     - simple-crud-network
  #   restart: always
  #   environment:
  #     POSTGRES_USER: pguser
  #     POSTGRES_PASSWORD: pgpassword

  # adminer:
  #   image: adminer
  #   container_name: adminer
  #   networks:
  #     - simple-crud-network
  #   restart: always
  #   ports:
  #     - 8000:8080

networks:
  simple-crud-network:
    driver: bridge